version: "3.8"
services:
  backend:
    build: ./kennel_app   # Path to the backend Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=db

  frontend:
    build: ./frontend     # Path to the frontend Dockerfile
    ports:
      - "3000:5000"       # Host port 3000 to container port 5000
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"       # Changed host port to 5433 to avoid conflicts
